### ISSUE TITLE
master分支中代码问题

### ISSUE THREAD

**Issue by PhilOkami** [TF2-Engine/TF2#10]
1.代码位置：（模型转换部分） TF2/TransForm_Kit/ModelConvert/caffe2fpga/src/ 

问题一：其中所有的C++和头文件中版权信息注释使用方式有问题。

问题二：其中的caffe2fpga.cpp中 99行 float weight = blob.data()[j]; 
请问blob是做什么用的？这个地方使用方式是不是有点问题？

2.代码位置：（量化部分） TF2/TransForm_Kit/Quantization/quantization.py

问题一：QuantizeChannel函数中使用到了QuantizeLinear函数，但是QuantizeLinear函数并没有重载为两参的？或者说这个函数本来就是两参的函数，上边的这个函数就定义错了。

问题二：在上述两个函数中都使用到了n这个参数，但是并没有作相关定义？参数n的作用是什么？

**Comment by TF2-Engine** [comment]
关于量化部分，这里的n是为了将feature量化为不同bit而设置的，n=8的时候，原先程序中的Limiter=127，即进行INT8量化。目前程序已更新，统一去掉了n这个参数，不再设置不同的量化位宽，默认为INT8量化。

**Comment by TF2-Engine** [comment]
关于模型转换部分：
1、头文件和源文件中的版权注释已经修改；
2、blob是caffe中所有数据块的一个类，blob是权重数据、featuremap数据的表示方法；
再次感谢您的提问
