### ISSUE TITLE
FPGA board and tutorial question

### ISSUE THREAD

**Issue by jinz2014** [TF2-Engine/TF2#12]
May I evaluation your CNN application on an Intel PAC or Nallatech 385A FPGA board ?  Is it board specific ? 

In addition, could you please provide a tutorial on how users can convert, quantize, and run a Squeezenet model on an FPGA board ? 

Thank you!

**Comment by TF2-Engine** [comment]
1. As long as the memory and other hardware resources on board is adequete, any board supporting OpenCL platform is suitable for TF2.
2. We will publish a brief tutorial on the whole process on this github project soon.

**Comment by TF2-Engine** [comment]
Please refer to doc/A_Brief_Guide_on_Implementing_a_New_Model_in_TF2.txt.

**Comment by jinz2014** [comment]
Thanks again.
