### ISSUE TITLE
分支191_googlenet仿真运行core_dump

### ISSUE THREAD

**Issue by affectionlu** [TF2-Engine/TF2#18]
### 问题一：
环境：quartus 19.1
![image](https://user-images.githubusercontent.com/30404405/87133821-73c9aa80-c2ca-11ea-89df-721bb8826da7.png)

错误如下：
![image](https://user-images.githubusercontent.com/30404405/87133932-9956b400-c2ca-11ea-8aac-21bdb3a4ae66.png)

不知道是代码有问题还是软硬件版本的原因
@gaofeng-tf2 
@TF2-Engine

**Comment by affectionlu** [comment]
所在目录： TF2/Runtime_Engine/cnn/host
运行命令：CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ../bin/host ../host/model/googlenet/param.bin ../host/model/googlenet_Q ../host/test_images/googlenet_data_label_391.bin ../host/verify/googlenet_fc1000_label_391.bin 1

**Comment by affectionlu** [comment]
在winograd_191分支也有这个core_dump,请问这是啥原因啊

**Comment by TF2-Engine** [comment]
191_googlenet branch is under developping, please use 191 branch with resnet50 network instead （aoc DRESNET50=1, make RESNET50=1）.
winograd_191 works well here both in hardware mode and emulation mode. Please make sure that your version is the latest commit.

**Comment by affectionlu** [comment]
Thanks!
