### ISSUE TITLE
what will be quantified in TF2

### ISSUE THREAD

**Issue by zhaohb** [TF2-Engine/TF2#4]
Now I am reading the code of TF2, I found in Runtime_Engine/cnn/host/src/network.cpp will call quantization function, but I also found in TransForm_Kit will do quantization, 
what's the difference between them and what's the difference in the way they quantify?

**Comment by TF2-Engine** [comment]
Transform Kit realizes the quantization and saves the quantization parameters into quantization file. Runtime Engine reads the quantization file.

**Comment by zhaohb** [comment]
in input_loader.cpp input_raw[C][H][W] will trans to input[CEIL(C, C_VECTOR)][H][CEIL(W, W_VECTOR)][W_VECTOR][C_VECTOR], why?
