### ISSUE TITLE
关于运行Run_Engine的问题

### ISSUE THREAD

**Issue by xiayewanfeng** [TF2-Engine/TF2#9]
在Run_Engine下面的手册说明了如何在evaluation mode和running mode下运行。我想请问您一下：
1、#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/<your_model_file_path> ../host/model/<your_quantization_file_path> ../host/test_images/<your_test_file_path> 这条指令是用于传递参数的吗？ 为什么我的文件夹里没有 ./bin/host路径
2、除了按照手册上面的进入两种mode外，需要运行run.sh文件吗？希望您可以将Run_Enigne的运行手册写的详细一点。谢谢

**Comment by TF2-Engine** [comment]
1. This command aims to set the parameters and run the evaluation executive. The ./bin/host will be generated after running the "make" command in cnn/.
2. All the shell script files like run.sh are supplied as examples of command lines. Hence you do not have to use it.
